name: Generate documentation

# only trigger this action on specific events
on:
  push:
    branches:
      - master
      - add_doxygen
  pull_request:
    branches:
      - master

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout cppuddle
        uses: actions/checkout@v2
        with:
          path: cppuddle
      # install dependencies
      - name: Dependancies
        run: |
          sudo apt update
          sudo apt-get install -y doxygen graphviz
      # configure project via CMake
      - name: Configure
        run: |
          cd cppuddle
          mkdir build
          cd build
          cmake -CPPUDDLE_WITH_DOCUMENTATION=ON ..
      # build project
      - name: Generate
        run: |
          cd cppuddle/build
          make doc
      # deploy generated documentation using github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cppuddle/docs/html
