#!groovy
pipeline {
    agent { label 'pcsgs05' }

    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "21",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "21",
                artifactNumToKeepStr: "50"
            )
        )
    }
    environment {
        GITHUB_TOKEN = credentials('GITHUB_TOKEN_OCTOTIGER')
    }
    stages {
        stage('init') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        github_token=$(echo ${GITHUB_TOKEN} | cut -f2 -d':')
                        curl --verbose\
                            --request POST \
                            --url "https://api.github.com/repos/SC-SGS/CPPuddle/statuses/$GIT_COMMIT" \
                            --header "Content-Type: application/json" \
                            --header "authorization: Bearer ${github_token}" \
                            --data "{
                                \\"state\\": \\"pending\\",
                                \\"context\\": \\"jenkins-CPU-GPU-tests\\",
                                \\"description\\": \\"Jenkins CI Job: jenkins-CPU-GPU-tests\\",
                                \\"target_url\\": \\"https://simsgs.informatik.uni-stuttgart.de/jenkins/job/CPPuddle/$BUILD_NUMBER/console\\"
                        }"
                    '''
                }
            }
        }
        stage('checkout') {
            steps {
                dir('CPPuddle') {
                    checkout scm
                }
            }
        }
        stage('build-submodules') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda
                        git submodule update --init --recursive
                        ./scripts/build_dependencies.sh
                    '''
                }
            }
        }
        stage('build cppuddle') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda 
                        ./scripts/configure_build_directory.sh
                        cd build/Release
                        make -j2
                    '''
                }
            }
        }
        stage('run tests') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda
                        cd build/Release
                        ctest -j2
                    '''
                }
            }
        }
    }
    post {
        success {
            sh '''
                github_token=$(echo ${GITHUB_TOKEN} | cut -f2 -d':')
                curl --verbose\
                    --request POST \
                    --url "https://api.github.com/repos/SC-SGS/CPPuddle/statuses/$GIT_COMMIT" \
                    --header "Content-Type: application/json" \
                    --header "authorization: Bearer ${github_token}" \
                    --data "{
                        \\"state\\": \\"success\\",
                        \\"context\\": \\"jenkins-CPU-GPU-tests\\",
                        \\"description\\": \\"Jenkins CI Job: jenkins-CPU-GPU-tests\\",
                        \\"target_url\\": \\"https://simsgs.informatik.uni-stuttgart.de/jenkins/job/CPPuddle/$BUILD_NUMBER/console\\"
                }"
            '''
        }
        failure {
            sh '''
                github_token=$(echo ${GITHUB_TOKEN} | cut -f2 -d':')
                curl --verbose\
                    --request POST \
                    --url "https://api.github.com/repos/SC-SGS/CPPuddle/statuses/$GIT_COMMIT" \
                    --header "Content-Type: application/json" \
                    --header "authorization: Bearer ${github_token}" \
                    --data "{
                        \\"state\\": \\"failure\\",
                        \\"context\\": \\"jenkins-CPU-GPU-tests\\",
                        \\"description\\": \\"Jenkins CI Job: jenkins-CPU-GPU-tests\\",
                        \\"target_url\\": \\"https://simsgs.informatik.uni-stuttgart.de/jenkins/job/CPPuddle/$BUILD_NUMBER/console\\"
                }"
            '''
        }
        aborted {
            sh '''
                github_token=$(echo ${GITHUB_TOKEN} | cut -f2 -d':')
                curl --verbose\
                    --request POST \
                    --url "https://api.github.com/repos/SC-SGS/CPPuddle/statuses/$GIT_COMMIT" \
                    --header "Content-Type: application/json" \
                    --header "authorization: Bearer ${github_token}" \
                    --data "{
                        \\"state\\": \\"error\\",
                        \\"context\\": \\"jenkins-CPU-GPU-tests\\",
                        \\"description\\": \\"Jenkins CI Job: jenkins-CPU-GPU-tests\\",
                        \\"target_url\\": \\"https://simsgs.informatik.uni-stuttgart.de/jenkins/job/CPPuddle/$BUILD_NUMBER/console\\"
                }"
            '''
        }
    }
}
