#!groovy
pipeline {
    agent { label 'pcsgs05' }

    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "21",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "21",
                artifactNumToKeepStr: "50"
            )
        )
    }
    stages {
        stage('checkout') {
            steps {
                dir('CPPuddle') {
                    checkout scm
                }
            }
        }
        stage('build-submodules') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda
                        git submodule update --init --recursive
                        ./scripts/build_dependencies.sh
                    '''
                }
            }
        }
        stage('build cppuddle') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda 
                        ./scripts/configure_build_directory.sh
                        cd build/Release
                        make -j2
                    '''
                }
            }
        }
        stage('run tests') {
            steps {
                dir('CPPuddle') {
                    sh '''
                        module load cuda
                        cd build/Release
                        ctest -j2
                    '''
                }
            }
        }
    }
}
